// file location: src/lib/database/schemaReference.js
// This file mirrors the database schema shared during the HR module scaffolding discussion.
// Each entry represents a single column definition with its table, data type, nullability, and default.

export const databaseColumns = [
  { table_name: "User table", column_name: "id", data_type: "bigint", is_nullable: "NO", column_default: null },
  { table_name: "User table", column_name: "created_at", data_type: "timestamp with time zone", is_nullable: "NO", column_default: "now()" },
  { table_name: "activity_logs", column_name: "log_id", data_type: "integer", is_nullable: "NO", column_default: "nextval('activity_logs_log_id_seq'::regclass)" },
  { table_name: "activity_logs", column_name: "user_id", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "activity_logs", column_name: "action", data_type: "character varying", is_nullable: "YES", column_default: null },
  { table_name: "activity_logs", column_name: "table_name", data_type: "character varying", is_nullable: "YES", column_default: null },
  { table_name: "activity_logs", column_name: "record_id", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "activity_logs", column_name: "timestamp", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "appointments", column_name: "appointment_id", data_type: "integer", is_nullable: "NO", column_default: "nextval('appointments_appointment_id_seq'::regclass)" },
  { table_name: "appointments", column_name: "job_id", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "appointments", column_name: "customer_id", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "appointments", column_name: "scheduled_time", data_type: "timestamp with time zone", is_nullable: "NO", column_default: null },
  { table_name: "appointments", column_name: "status", data_type: "character varying", is_nullable: "YES", column_default: "'booked'::character varying" },
  { table_name: "appointments", column_name: "notes", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "appointments", column_name: "created_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "appointments", column_name: "updated_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "customers", column_name: "id", data_type: "uuid", is_nullable: "NO", column_default: "gen_random_uuid()" },
  { table_name: "customers", column_name: "firstname", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "customers", column_name: "lastname", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "customers", column_name: "email", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "customers", column_name: "mobile", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "customers", column_name: "telephone", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "customers", column_name: "address", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "customers", column_name: "postcode", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "customers", column_name: "created_at", data_type: "timestamp without time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "customers", column_name: "contact_preference", data_type: "text", is_nullable: "YES", column_default: "'email'::text" },
  { table_name: "customers", column_name: "updated_at", data_type: "timestamp without time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "customers", column_name: "name", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_clocking", column_name: "id", data_type: "integer", is_nullable: "NO", column_default: "nextval('job_clocking_id_seq'::regclass)" },
  { table_name: "job_clocking", column_name: "user_id", data_type: "integer", is_nullable: "NO", column_default: null },
  { table_name: "job_clocking", column_name: "job_id", data_type: "integer", is_nullable: "NO", column_default: null },
  { table_name: "job_clocking", column_name: "job_number", data_type: "text", is_nullable: "NO", column_default: null },
  { table_name: "job_clocking", column_name: "clock_in", data_type: "timestamp with time zone", is_nullable: "NO", column_default: null },
  { table_name: "job_clocking", column_name: "clock_out", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
  { table_name: "job_clocking", column_name: "work_type", data_type: "text", is_nullable: "NO", column_default: "'initial'::text" },
  { table_name: "job_clocking", column_name: "created_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "job_clocking", column_name: "updated_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "job_files", column_name: "file_id", data_type: "integer", is_nullable: "NO", column_default: "nextval('job_files_file_id_seq'::regclass)" },
  { table_name: "job_files", column_name: "job_id", data_type: "integer", is_nullable: "NO", column_default: null },
  { table_name: "job_files", column_name: "file_name", data_type: "text", is_nullable: "NO", column_default: null },
  { table_name: "job_files", column_name: "file_url", data_type: "text", is_nullable: "NO", column_default: null },
  { table_name: "job_files", column_name: "file_type", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_files", column_name: "uploaded_by", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "job_files", column_name: "folder", data_type: "text", is_nullable: "YES", column_default: "'general'::text" },
  { table_name: "job_files", column_name: "uploaded_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "job_notes", column_name: "note_id", data_type: "integer", is_nullable: "NO", column_default: "nextval('job_notes_note_id_seq'::regclass)" },
  { table_name: "job_notes", column_name: "job_id", data_type: "integer", is_nullable: "NO", column_default: null },
  { table_name: "job_notes", column_name: "user_id", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "job_notes", column_name: "note_text", data_type: "text", is_nullable: "NO", column_default: null },
  { table_name: "job_notes", column_name: "created_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "job_notes", column_name: "updated_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "job_status_history", column_name: "id", data_type: "integer", is_nullable: "NO", column_default: "nextval('job_status_history_id_seq'::regclass)" },
  { table_name: "job_status_history", column_name: "job_id", data_type: "integer", is_nullable: "NO", column_default: null },
  { table_name: "job_status_history", column_name: "from_status", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_status_history", column_name: "to_status", data_type: "text", is_nullable: "NO", column_default: null },
  { table_name: "job_status_history", column_name: "changed_by", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_status_history", column_name: "reason", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_status_history", column_name: "changed_at", data_type: "timestamp with time zone", is_nullable: "NO", column_default: "now()" },
  { table_name: "job_status_timeline", column_name: "job_id", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "job_status_timeline", column_name: "job_number", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_status_timeline", column_name: "from_status", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_status_timeline", column_name: "to_status", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_status_timeline", column_name: "changed_by", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_status_timeline", column_name: "reason", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_status_timeline", column_name: "changed_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
  { table_name: "job_status_timeline", column_name: "next_change", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
  { table_name: "job_status_timeline", column_name: "hours_in_status", data_type: "numeric", is_nullable: "YES", column_default: null },
  { table_name: "job_writeups", column_name: "writeup_id", data_type: "integer", is_nullable: "NO", column_default: "nextval('job_writeups_writeup_id_seq'::regclass)" },
  { table_name: "job_writeups", column_name: "job_id", data_type: "integer", is_nullable: "NO", column_default: null },
  { table_name: "job_writeups", column_name: "technician_id", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "job_writeups", column_name: "work_performed", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_writeups", column_name: "parts_used", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_writeups", column_name: "recommendations", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_writeups", column_name: "labour_time", data_type: "numeric", is_nullable: "YES", column_default: null },
  { table_name: "job_writeups", column_name: "created_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "job_writeups", column_name: "updated_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "job_writeups", column_name: "ratification", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_writeups", column_name: "warranty_claim", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_writeups", column_name: "tsr_number", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_writeups", column_name: "pwa_number", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_writeups", column_name: "technical_bulletins", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_writeups", column_name: "technical_signature", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_writeups", column_name: "quality_control", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_writeups", column_name: "qty", data_type: "jsonb", is_nullable: "YES", column_default: "'[]'::jsonb" },
  { table_name: "job_writeups", column_name: "booked", data_type: "jsonb", is_nullable: "YES", column_default: "'[]'::jsonb" },
  { table_name: "job_writeups", column_name: "completion_status", data_type: "text", is_nullable: "YES", column_default: "'additional_work'::text" },
  { table_name: "job_writeups", column_name: "rectification_notes", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_writeups", column_name: "job_description_snapshot", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "job_writeups", column_name: "vhc_authorization_reference", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "job_writeups", column_name: "task_checklist", data_type: "jsonb", is_nullable: "YES", column_default: "'[]'::jsonb" },
  { table_name: "job_writeup_tasks", column_name: "task_id", data_type: "bigint", is_nullable: "NO", column_default: "nextval('job_writeup_tasks_task_id_seq'::regclass)" },
  { table_name: "job_writeup_tasks", column_name: "job_id", data_type: "integer", is_nullable: "NO", column_default: null },
  { table_name: "job_writeup_tasks", column_name: "source", data_type: "text", is_nullable: "NO", column_default: null },
  { table_name: "job_writeup_tasks", column_name: "source_key", data_type: "text", is_nullable: "NO", column_default: null },
  { table_name: "job_writeup_tasks", column_name: "label", data_type: "text", is_nullable: "NO", column_default: null },
  { table_name: "job_writeup_tasks", column_name: "status", data_type: "text", is_nullable: "NO", column_default: "'additional_work'::text" },
  { table_name: "job_writeup_tasks", column_name: "created_at", data_type: "timestamp with time zone", is_nullable: "NO", column_default: "now()" },
  { table_name: "job_writeup_tasks", column_name: "updated_at", data_type: "timestamp with time zone", is_nullable: "NO", column_default: "now()" },
  { table_name: "jobs", column_name: "id", data_type: "integer", is_nullable: "NO", column_default: "nextval('jobs_id_seq'::regclass)" },
  { table_name: "jobs", column_name: "customer", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "customer_id", data_type: "uuid", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "vehicle_reg", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "vehicle_make_model", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "waiting_status", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "job_source", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "job_categories", data_type: "ARRAY", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "requests", data_type: "jsonb", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "created_at", data_type: "timestamp without time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "jobs", column_name: "job_number", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "vehicle_id", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "description", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "type", data_type: "text", is_nullable: "YES", column_default: "'Service'::text" },
  { table_name: "jobs", column_name: "status", data_type: "text", is_nullable: "YES", column_default: "'New'::text" },
  { table_name: "jobs", column_name: "assigned_to", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "updated_at", data_type: "timestamp without time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "jobs", column_name: "cosmetic_notes", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "vhc_required", data_type: "boolean", is_nullable: "YES", column_default: "false" },
  { table_name: "jobs", column_name: "maintenance_info", data_type: "jsonb", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "status_updated_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "status_updated_by", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "checked_in_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "workshop_started_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "vhc_completed_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "vhc_sent_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "additional_work_authorized_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "additional_work_started_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "wash_started_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "completed_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "parts_ordered_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "warranty_parts_ordered_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "warranty_qc_started_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
  { table_name: "jobs", column_name: "warranty_ready_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
  { table_name: "messages", column_name: "message_id", data_type: "integer", is_nullable: "NO", column_default: "nextval('messages_message_id_seq'::regclass)" },
  { table_name: "messages", column_name: "sender_id", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "messages", column_name: "receiver_id", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "messages", column_name: "content", data_type: "text", is_nullable: "NO", column_default: null },
  { table_name: "messages", column_name: "read", data_type: "boolean", is_nullable: "YES", column_default: "false" },
  { table_name: "messages", column_name: "created_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "messages", column_name: "thread_id", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "message_threads", column_name: "thread_id", data_type: "integer", is_nullable: "NO", column_default: "nextval('message_threads_thread_id_seq'::regclass)" },
  { table_name: "message_threads", column_name: "thread_type", data_type: "text", is_nullable: "NO", column_default: "'direct'::text" },
  { table_name: "message_threads", column_name: "title", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "message_threads", column_name: "unique_hash", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "message_threads", column_name: "created_by", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "message_threads", column_name: "created_at", data_type: "timestamp with time zone", is_nullable: "NO", column_default: "now()" },
  { table_name: "message_threads", column_name: "updated_at", data_type: "timestamp with time zone", is_nullable: "NO", column_default: "now()" },
  { table_name: "message_thread_members", column_name: "member_id", data_type: "integer", is_nullable: "NO", column_default: "nextval('message_thread_members_member_id_seq'::regclass)" },
  { table_name: "message_thread_members", column_name: "thread_id", data_type: "integer", is_nullable: "NO", column_default: null },
  { table_name: "message_thread_members", column_name: "user_id", data_type: "integer", is_nullable: "NO", column_default: null },
  { table_name: "message_thread_members", column_name: "role", data_type: "text", is_nullable: "NO", column_default: "'member'::text" },
  { table_name: "message_thread_members", column_name: "joined_at", data_type: "timestamp with time zone", is_nullable: "NO", column_default: "now()" },
  { table_name: "message_thread_members", column_name: "last_read_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
  { table_name: "notifications", column_name: "notification_id", data_type: "integer", is_nullable: "NO", column_default: "nextval('notifications_notification_id_seq'::regclass)" },
  { table_name: "notifications", column_name: "user_id", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "notifications", column_name: "type", data_type: "character varying", is_nullable: "YES", column_default: null },
  { table_name: "notifications", column_name: "message", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "notifications", column_name: "read", data_type: "boolean", is_nullable: "YES", column_default: "false" },
  { table_name: "notifications", column_name: "created_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "parts_inventory", column_name: "part_id", data_type: "integer", is_nullable: "NO", column_default: "nextval('parts_inventory_part_id_seq'::regclass)" },
  { table_name: "parts_inventory", column_name: "part_number", data_type: "character varying", is_nullable: "NO", column_default: null },
  { table_name: "parts_inventory", column_name: "name", data_type: "character varying", is_nullable: "YES", column_default: null },
  { table_name: "parts_inventory", column_name: "description", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "parts_inventory", column_name: "quantity", data_type: "integer", is_nullable: "YES", column_default: "0" },
  { table_name: "parts_inventory", column_name: "price", data_type: "numeric", is_nullable: "YES", column_default: null },
  { table_name: "parts_inventory", column_name: "created_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "parts_inventory", column_name: "updated_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "parts_requests", column_name: "request_id", data_type: "integer", is_nullable: "NO", column_default: "nextval('parts_requests_request_id_seq'::regclass)" },
  { table_name: "parts_requests", column_name: "job_id", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "parts_requests", column_name: "part_id", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "parts_requests", column_name: "requested_by", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "parts_requests", column_name: "approved_by", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "parts_requests", column_name: "quantity", data_type: "integer", is_nullable: "YES", column_default: "1" },
  { table_name: "parts_requests", column_name: "status", data_type: "character varying", is_nullable: "YES", column_default: "'pending'::character varying" },
  { table_name: "parts_requests", column_name: "created_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "parts_requests", column_name: "updated_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "sales_tracking", column_name: "sale_id", data_type: "integer", is_nullable: "NO", column_default: "nextval('sales_tracking_sale_id_seq'::regclass)" },
  { table_name: "sales_tracking", column_name: "vehicle_id", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "sales_tracking", column_name: "sold_by", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "sales_tracking", column_name: "price", data_type: "numeric", is_nullable: "YES", column_default: null },
  { table_name: "sales_tracking", column_name: "sold_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "sales_tracking", column_name: "created_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "schema_migrations", column_name: "id", data_type: "integer", is_nullable: "NO", column_default: "nextval('schema_migrations_id_seq'::regclass)" },
  { table_name: "schema_migrations", column_name: "migration_name", data_type: "text", is_nullable: "NO", column_default: null },
  { table_name: "schema_migrations", column_name: "applied_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "users", column_name: "user_id", data_type: "integer", is_nullable: "NO", column_default: "nextval('users_user_id_seq'::regclass)" },
  { table_name: "users", column_name: "first_name", data_type: "character varying", is_nullable: "NO", column_default: null },
  { table_name: "users", column_name: "last_name", data_type: "character varying", is_nullable: "NO", column_default: null },
  { table_name: "users", column_name: "email", data_type: "character varying", is_nullable: "NO", column_default: null },
  { table_name: "users", column_name: "password_hash", data_type: "character varying", is_nullable: "NO", column_default: null },
  { table_name: "users", column_name: "role", data_type: "character varying", is_nullable: "NO", column_default: null },
  { table_name: "users", column_name: "phone", data_type: "character varying", is_nullable: "YES", column_default: null },
  { table_name: "users", column_name: "created_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "users", column_name: "updated_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "vehicles", column_name: "vehicle_id", data_type: "integer", is_nullable: "NO", column_default: "nextval('vehicles_vehicle_id_seq'::regclass)" },
  { table_name: "vehicles", column_name: "reg_number", data_type: "character varying", is_nullable: "NO", column_default: null },
  { table_name: "vehicles", column_name: "make", data_type: "character varying", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "model", data_type: "character varying", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "year", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "vin", data_type: "character varying", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "owner_id", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "created_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "vehicles", column_name: "updated_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "vehicles", column_name: "colour", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "engine_number", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "mileage", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "fuel_type", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "transmission", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "body_style", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "mot_due", data_type: "date", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "service_history", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "warranty_type", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "warranty_expiry", data_type: "date", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "insurance_provider", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "insurance_policy_number", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "customer_id", data_type: "uuid", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "registration", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "make_model", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "chassis", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vehicles", column_name: "engine", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vhc_authorizations", column_name: "id", data_type: "integer", is_nullable: "NO", column_default: "nextval('vhc_authorizations_id_seq'::regclass)" },
  { table_name: "vhc_authorizations", column_name: "job_id", data_type: "integer", is_nullable: "NO", column_default: null },
  { table_name: "vhc_authorizations", column_name: "authorized_by", data_type: "text", is_nullable: "NO", column_default: null },
  { table_name: "vhc_authorizations", column_name: "authorized_at", data_type: "timestamp with time zone", is_nullable: "NO", column_default: "now()" },
  { table_name: "vhc_authorizations", column_name: "authorized_items", data_type: "jsonb", is_nullable: "YES", column_default: "'[]'::jsonb" },
  { table_name: "vhc_authorizations", column_name: "customer_notes", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vhc_authorizations", column_name: "created_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "vhc_checks", column_name: "vhc_id", data_type: "integer", is_nullable: "NO", column_default: "nextval('vhc_checks_vhc_id_seq'::regclass)" },
  { table_name: "vhc_checks", column_name: "job_id", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "vhc_checks", column_name: "section", data_type: "character varying", is_nullable: "YES", column_default: null },
  { table_name: "vhc_checks", column_name: "issue_title", data_type: "character varying", is_nullable: "YES", column_default: null },
  { table_name: "vhc_checks", column_name: "issue_description", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vhc_checks", column_name: "measurement", data_type: "character varying", is_nullable: "YES", column_default: null },
  { table_name: "vhc_checks", column_name: "created_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "vhc_checks", column_name: "updated_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "vhc_declinations", column_name: "id", data_type: "integer", is_nullable: "NO", column_default: "nextval('vhc_declinations_id_seq'::regclass)" },
  { table_name: "vhc_declinations", column_name: "job_id", data_type: "integer", is_nullable: "NO", column_default: null },
  { table_name: "vhc_declinations", column_name: "declined_by", data_type: "text", is_nullable: "NO", column_default: null },
  { table_name: "vhc_declinations", column_name: "declined_at", data_type: "timestamp with time zone", is_nullable: "NO", column_default: "now()" },
  { table_name: "vhc_declinations", column_name: "customer_notes", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vhc_declinations", column_name: "created_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "vhc_send_history", column_name: "id", data_type: "integer", is_nullable: "NO", column_default: "nextval('vhc_send_history_id_seq'::regclass)" },
  { table_name: "vhc_send_history", column_name: "job_id", data_type: "integer", is_nullable: "NO", column_default: null },
  { table_name: "vhc_send_history", column_name: "sent_by", data_type: "text", is_nullable: "NO", column_default: null },
  { table_name: "vhc_send_history", column_name: "sent_at", data_type: "timestamp with time zone", is_nullable: "NO", column_default: "now()" },
  { table_name: "vhc_send_history", column_name: "send_method", data_type: "text", is_nullable: "YES", column_default: "'email'::text" },
  { table_name: "vhc_send_history", column_name: "customer_email", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vhc_send_history", column_name: "created_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: "now()" },
  { table_name: "vhc_workflow_status", column_name: "job_id", data_type: "integer", is_nullable: "YES", column_default: null },
  { table_name: "vhc_workflow_status", column_name: "job_number", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vhc_workflow_status", column_name: "vehicle_reg", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vhc_workflow_status", column_name: "status", data_type: "text", is_nullable: "YES", column_default: null },
  { table_name: "vhc_workflow_status", column_name: "vhc_required", data_type: "boolean", is_nullable: "YES", column_default: null },
  { table_name: "vhc_workflow_status", column_name: "vhc_checks_count", data_type: "bigint", is_nullable: "YES", column_default: null },
  { table_name: "vhc_workflow_status", column_name: "last_sent_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
  { table_name: "vhc_workflow_status", column_name: "authorization_count", data_type: "bigint", is_nullable: "YES", column_default: null },
  { table_name: "vhc_workflow_status", column_name: "declination_count", data_type: "bigint", is_nullable: "YES", column_default: null },
  { table_name: "vhc_workflow_status", column_name: "vhc_completed_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
  { table_name: "vhc_workflow_status", column_name: "vhc_sent_at", data_type: "timestamp with time zone", is_nullable: "YES", column_default: null },
];
