// Mock rows for the GDPR / data-protection registers surfaced under
// /admin/compliance. Column names match the real Supabase register tables
// (breach_records, dpia_records, retention_policies, retention_runs,
// processing_activities, subject_requests) so the page handlers render
// unchanged in presentation mode.

const iso = (daysAgo) =>
  new Date(Date.now() - daysAgo * 24 * 60 * 60 * 1000).toISOString();

// breach_records — personal-data breach log.
export const breachRecords = [
  {
    id: "demo-breach-001",
    detected_at: iso(12),
    reported_internally_at: iso(12),
    ico_notified_at: iso(11),
    ico_reference: "ICO-2026-00417",
    subjects_notified_at: iso(10),
    category: "Misdirected email",
    severity: "Medium",
    root_cause: "Service reminder sent to a previous keeper after a vehicle changed hands.",
    affected_count: 1,
    data_categories_affected: ["Contact details", "Vehicle registration"],
    containment_actions: "Recalled the email and corrected the vehicle's customer link.",
    remediation_actions: "Added a change-of-keeper check to the reminder workflow.",
    reportable_to_ico: true,
    reportable_to_subjects: true,
    decision_rationale: "Low volume and limited data — reported to the ICO for completeness.",
    status: "Closed",
    owner_user_id: 12,
  },
  {
    id: "demo-breach-002",
    detected_at: iso(3),
    reported_internally_at: iso(3),
    ico_notified_at: null,
    ico_reference: null,
    subjects_notified_at: null,
    category: "Lost device",
    severity: "Low",
    root_cause: "Workshop tablet left in a courtesy car overnight; recovered next morning.",
    affected_count: 0,
    data_categories_affected: ["None confirmed"],
    containment_actions: "Device remote-locked; encryption confirmed, no data accessed.",
    remediation_actions: "Reinforced the end-of-shift device sign-out policy.",
    reportable_to_ico: false,
    reportable_to_subjects: false,
    decision_rationale: "No unauthorised access and device encrypted — not reportable.",
    status: "Under review",
    owner_user_id: 12,
  },
  {
    id: "demo-breach-003",
    detected_at: iso(1),
    reported_internally_at: iso(1),
    ico_notified_at: null,
    ico_reference: null,
    subjects_notified_at: null,
    category: "Access misconfiguration",
    severity: "High",
    root_cause: "A reporting view briefly exposed payroll figures to a non-HR role.",
    affected_count: 11,
    data_categories_affected: ["Payroll", "Employment details"],
    containment_actions: "Revoked the role mapping and rotated the affected view.",
    remediation_actions: "Assessing whether subject notification is required.",
    reportable_to_ico: true,
    reportable_to_subjects: false,
    decision_rationale: "Within the 72-hour assessment window — decision pending.",
    status: "Open",
    owner_user_id: 12,
  },
];

// dpia_records — Data Protection Impact Assessments.
export const dpiaRecords = [
  {
    id: "demo-dpia-001",
    system_or_feature: "Vehicle Health Check customer share links",
    description: "Public, signed links that let customers view and approve VHC findings without an account.",
    status: "Approved",
    risk_level: "Medium",
    mitigations: "Time-limited signed tokens, no account data exposed, link revocation on completion.",
    signed_off_by: "Demo Admin Manager",
    signed_off_at: iso(40),
    next_review: iso(-325),
    document_url: "https://demo.invalid/dpia/vhc-share.pdf",
  },
  {
    id: "demo-dpia-002",
    system_or_feature: "Workshop CCTV and key-tracking",
    description: "Camera coverage of the workshop and RFID key-tracking for vehicles on site.",
    status: "Approved",
    risk_level: "Low",
    mitigations: "Signage in place, 30-day retention, access limited to managers.",
    signed_off_by: "Demo Owner",
    signed_off_at: iso(120),
    next_review: iso(-245),
    document_url: "https://demo.invalid/dpia/cctv.pdf",
  },
  {
    id: "demo-dpia-003",
    system_or_feature: "AI job-summary assistant",
    description: "Generative assistant that drafts customer-facing job summaries from technician notes.",
    status: "In progress",
    risk_level: "Medium",
    mitigations: "No data used for model training; output reviewed before sending.",
    signed_off_by: null,
    signed_off_at: null,
    next_review: iso(-14),
    document_url: null,
  },
];

// retention_policies — how long each entity type is kept.
export const retentionPolicies = [
  {
    id: "demo-rp-001",
    entity_type: "job_cards",
    retention_period: "7 years",
    legal_basis: "Legal obligation — motor trade and tax records",
    action: "Archive then delete",
    notes: "Retained for warranty and HMRC purposes.",
    reviewed_at: iso(60),
  },
  {
    id: "demo-rp-002",
    entity_type: "vhc_reports",
    retention_period: "3 years",
    legal_basis: "Legitimate interests — dispute resolution",
    action: "Delete",
    notes: "Linked media purged with the parent report.",
    reviewed_at: iso(60),
  },
  {
    id: "demo-rp-003",
    entity_type: "marketing_consents",
    retention_period: "Until withdrawn",
    legal_basis: "Consent",
    action: "Delete on withdrawal",
    notes: "Withdrawal honoured within 24 hours.",
    reviewed_at: iso(30),
  },
  {
    id: "demo-rp-004",
    entity_type: "cctv_footage",
    retention_period: "30 days",
    legal_basis: "Legitimate interests — site security",
    action: "Auto-delete",
    notes: "Rolling overwrite unless flagged for an incident.",
    reviewed_at: iso(90),
  },
];

// retention_runs — recent retention sweeps.
export const retentionRuns = [
  {
    id: "demo-run-001",
    ran_at: iso(2),
    entity_type: "cctv_footage",
    action: "Auto-delete",
    dry_run: false,
    rows_processed: 1840,
    rows_actioned: 1822,
    triggered_by: 12,
    notes: "Scheduled nightly sweep.",
  },
  {
    id: "demo-run-002",
    ran_at: iso(9),
    entity_type: "vhc_reports",
    action: "Delete",
    dry_run: true,
    rows_processed: 64,
    rows_actioned: 0,
    triggered_by: 12,
    notes: "Dry run ahead of the quarterly purge.",
  },
];

// processing_activities — Record of Processing Activities (ROPA).
export const processingActivities = [
  {
    id: "demo-ropa-001",
    name: "Service and repair job management",
    purpose: "Booking, carrying out and invoicing vehicle service and repair work.",
    lawful_basis: "Contract",
    data_categories: ["Contact details", "Vehicle details", "Payment records"],
    recipients: ["Parts suppliers", "Payment processor"],
    international_transfers: "None",
    security_measures: "Role-based access, encryption in transit, audit logging.",
    retention_summary: "7 years — see job_cards retention policy.",
    owner_user_id: 12,
    last_reviewed_at: iso(45),
    next_review_at: iso(-320),
  },
  {
    id: "demo-ropa-002",
    name: "Employee HR and payroll",
    purpose: "Managing employment records, attendance, leave and payroll.",
    lawful_basis: "Legal obligation / Contract",
    data_categories: ["Identity", "Bank details", "Attendance", "Disciplinary records"],
    recipients: ["HMRC", "Pension provider"],
    international_transfers: "None",
    security_measures: "HR-only access, separate payroll permissions, audit logging.",
    retention_summary: "6 years after employment ends.",
    owner_user_id: 11,
    last_reviewed_at: iso(70),
    next_review_at: iso(-295),
  },
  {
    id: "demo-ropa-003",
    name: "Marketing communications",
    purpose: "Sending service reminders and offers to customers who have opted in.",
    lawful_basis: "Consent",
    data_categories: ["Contact details", "Vehicle details"],
    recipients: ["Email delivery provider"],
    international_transfers: "None",
    security_measures: "Consent ledger, one-click unsubscribe, suppression list.",
    retention_summary: "Until consent is withdrawn.",
    owner_user_id: 12,
    last_reviewed_at: iso(20),
    next_review_at: iso(-345),
  },
];

// subject_requests — Subject Access / data-rights requests.
export const subjectRequests = [
  {
    id: "demo-sar-001",
    request_type: "access",
    status: "fulfilled",
    subject_email: "alex.morgan@demo.invalid",
    subject_user_id: null,
    identity_verification_method: "Photo ID + matching service record",
    response_artifact_url: "https://demo.invalid/sar/demo-sar-001.zip",
    rejection_reason: null,
    received_at: iso(26),
    due_at: iso(-4),
    fulfilled_at: iso(8),
    handled_by: 12,
  },
  {
    id: "demo-sar-002",
    request_type: "erasure",
    status: "in_progress",
    subject_email: "priya.shah@demo.invalid",
    subject_user_id: null,
    identity_verification_method: "Email confirmation",
    response_artifact_url: null,
    rejection_reason: null,
    received_at: iso(7),
    due_at: iso(-23),
    fulfilled_at: null,
    handled_by: 12,
  },
  {
    id: "demo-sar-003",
    request_type: "rectification",
    status: "received",
    subject_email: "tom.reynolds@demo.invalid",
    subject_user_id: null,
    identity_verification_method: null,
    response_artifact_url: null,
    rejection_reason: null,
    received_at: iso(1),
    due_at: iso(-29),
    fulfilled_at: null,
    handled_by: null,
  },
];

// Default export keeps parity with other mockData modules that expose `rows`;
// the compliance registers are multi-table, so `rows` points at the breach log.
export const rows = breachRecords;
