export const rows = [
  { id: "demo-emp-001", employee_number: "EMP-001", full_name: "Demo Tech",          job_title: "Senior Technician",       department: "Workshop",       email: "demo.tech@hnp.example",     phone: "07700 800001", start_date: "2022-04-04", status: "Active" },
  { id: "demo-emp-002", employee_number: "EMP-002", full_name: "Demo Manager",       job_title: "Workshop Manager",        department: "Workshop",       email: "demo.manager@hnp.example",  phone: "07700 800002", start_date: "2018-08-12", status: "Active" },
  { id: "demo-emp-003", employee_number: "EMP-003", full_name: "Demo Reception",     job_title: "Service Advisor",         department: "Front of House", email: "demo.recep@hnp.example",    phone: "07700 800003", start_date: "2024-01-10", status: "Active" },
  { id: "demo-emp-004", employee_number: "EMP-004", full_name: "Demo Parts",         job_title: "Parts Advisor",           department: "Parts",          email: "demo.parts@hnp.example",    phone: "07700 800004", start_date: "2023-06-01", status: "Active" },
  { id: "demo-emp-005", employee_number: "EMP-005", full_name: "Demo MOT",           job_title: "MOT Tester",              department: "MOT",            email: "demo.mot@hnp.example",      phone: "07700 800005", start_date: "2020-03-15", status: "Active" },
  { id: "demo-emp-006", employee_number: "EMP-006", full_name: "Demo Painter",       job_title: "Body Shop Technician",    department: "Body Shop",      email: "demo.painter@hnp.example",  phone: "07700 800006", start_date: "2021-11-22", status: "Active" },
  { id: "demo-emp-007", employee_number: "EMP-007", full_name: "Demo Valet",         job_title: "Valeter",                 department: "Valeting",       email: "demo.valet@hnp.example",    phone: "07700 800007", start_date: "2025-02-03", status: "Active" },
  { id: "demo-emp-008", employee_number: "EMP-008", full_name: "Demo Mobile",        job_title: "Mobile Technician",       department: "Mobile",         email: "demo.mobile@hnp.example",   phone: "07700 800008", start_date: "2023-09-01", status: "Active" },
  { id: "demo-emp-009", employee_number: "EMP-009", full_name: "Demo Accounts",      job_title: "Accounts Manager",        department: "Accounts",       email: "demo.accounts@hnp.example", phone: "07700 800009", start_date: "2019-07-08", status: "Active" },
  { id: "demo-emp-010", employee_number: "EMP-010", full_name: "Demo Tech 2",        job_title: "Apprentice Technician",   department: "Workshop",       email: "demo.tech2@hnp.example",    phone: "07700 800010", start_date: "2025-08-12", status: "Active" },
];
