// Mock rows for the `jobs` Supabase table. Column names must match the real
// schema so .select(...) projections and downstream handlers work unchanged.
const rawRows = [
  { id: "demo-job-001", job_number: "DEMO-1042", customer_id: "demo-cust-001", vehicle_id: "demo-veh-001", reg: "DE24 XYZ", customer_name: "Alex Morgan",   make: "Volkswagen", model: "Golf",       complaint: "Knocking noise from front suspension, also due for major service.", status: "In Progress",         assigned_technician: "Demo Tech",   booked_in: "2026-04-22T08:30:00.000Z", estimated_completion: "2026-04-22T16:30:00.000Z", mileage: 41280, created_at: "2026-04-22T08:30:00.000Z", updated_at: "2026-04-22T11:30:00.000Z" },
  { id: "demo-job-002", job_number: "DEMO-1043", customer_id: "demo-cust-002", vehicle_id: "demo-veh-002", reg: "TA23 ABC", customer_name: "Priya Shah",    make: "Ford",       model: "Kuga",       complaint: "Engine management light, intermittent power loss.",                  status: "Awaiting Parts",       assigned_technician: "Demo Tech",   booked_in: "2026-04-21T10:00:00.000Z", estimated_completion: "2026-04-23T15:00:00.000Z", mileage: 28640, created_at: "2026-04-21T10:00:00.000Z", updated_at: "2026-04-22T09:15:00.000Z" },
  { id: "demo-job-003", job_number: "DEMO-1044", customer_id: "demo-cust-003", vehicle_id: "demo-veh-003", reg: "TV22 HNP", customer_name: "Tom Reynolds",  make: "BMW",        model: "3 Series",   complaint: "Annual service + MOT.",                                              status: "Complete",             assigned_technician: "Demo Tech",   booked_in: "2026-04-22T07:45:00.000Z", estimated_completion: "2026-04-22T12:00:00.000Z", completed_at: "2026-05-10T12:00:00.000Z", mileage: 52110, created_at: "2026-04-22T07:45:00.000Z", updated_at: "2026-04-22T12:00:00.000Z" },
  { id: "demo-job-004", job_number: "DEMO-1045", customer_id: "demo-cust-004", vehicle_id: "demo-veh-004", reg: "WS24 GLS", customer_name: "Sarah Bennett", make: "Audi",       model: "A3",         complaint: "Brake fluid change + front pads.",                                   status: "Booked In",            assigned_technician: "Demo Tech 2", booked_in: "2026-04-23T08:00:00.000Z", estimated_completion: "2026-04-23T13:00:00.000Z", mileage: 33420, created_at: "2026-04-20T14:00:00.000Z", updated_at: "2026-04-22T13:00:00.000Z" },
  { id: "demo-job-005", job_number: "DEMO-1046", customer_id: "demo-cust-005", vehicle_id: "demo-veh-005", reg: "LB23 RTV", customer_name: "James Holt",    make: "Mercedes",   model: "C-Class",    complaint: "AC not cold, suspect compressor.",                                   status: "Diagnostics",          assigned_technician: "Demo Tech",   booked_in: "2026-04-22T09:15:00.000Z", estimated_completion: "2026-04-23T17:00:00.000Z", mileage: 47210, created_at: "2026-04-22T09:00:00.000Z", updated_at: "2026-04-22T13:30:00.000Z" },
  { id: "demo-job-006", job_number: "DEMO-1047", customer_id: "demo-cust-006", vehicle_id: "demo-veh-006", reg: "GA24 XPL", customer_name: "Helen Carter",  make: "Toyota",     model: "RAV4",       complaint: "Hybrid battery warning light.",                                      status: "Awaiting Parts",       assigned_technician: "Demo Tech 2", booked_in: "2026-04-19T11:00:00.000Z", estimated_completion: "2026-04-24T16:00:00.000Z", mileage: 64880, created_at: "2026-04-19T11:00:00.000Z", updated_at: "2026-04-22T14:00:00.000Z" },
  { id: "demo-job-007", job_number: "DEMO-1048", customer_id: "demo-cust-007", vehicle_id: "demo-veh-007", reg: "PL22 NHS", customer_name: "Mark Wilson",   make: "Nissan",     model: "Qashqai",    complaint: "Service + cambelt replacement.",                                     status: "Completed",            assigned_technician: "Demo Tech",   booked_in: "2026-04-21T08:00:00.000Z", estimated_completion: "2026-04-22T17:00:00.000Z", completed_at: "2026-05-11T17:00:00.000Z", mileage: 89150, created_at: "2026-04-21T08:00:00.000Z", updated_at: "2026-04-22T14:30:00.000Z" },
  { id: "demo-job-008", job_number: "DEMO-1049", customer_id: "demo-cust-008", vehicle_id: "demo-veh-008", reg: "EX23 CRS", customer_name: "Iris Patel",    make: "Honda",      model: "Civic",      complaint: "Rear washer not working + tyre wear.",                               status: "Invoiced",             assigned_technician: "Demo Tech 2", booked_in: "2026-04-22T10:00:00.000Z", estimated_completion: "2026-04-22T14:00:00.000Z", completed_at: "2026-05-09T14:00:00.000Z", mileage: 19800, created_at: "2026-04-22T10:00:00.000Z", updated_at: "2026-04-22T14:00:00.000Z" },
  { id: "demo-job-009", job_number: "DEMO-1050", customer_id: "demo-cust-001", vehicle_id: "demo-veh-009", reg: "RV23 EVS", customer_name: "Alex Morgan",   make: "Tesla",      model: "Model 3",    complaint: "12v battery replacement, software check.",                           status: "Collected",            assigned_technician: "Demo Tech",   booked_in: "2026-04-22T13:00:00.000Z", estimated_completion: "2026-04-22T15:30:00.000Z", completed_at: "2026-05-08T15:30:00.000Z", mileage: 25640, created_at: "2026-04-22T13:00:00.000Z", updated_at: "2026-04-22T15:30:00.000Z" },
  { id: "demo-job-010", job_number: "DEMO-1051", customer_id: "demo-cust-009", vehicle_id: "demo-veh-010", reg: "BX24 LNP", customer_name: "Owen Brooks",   make: "Land Rover", model: "Discovery",  complaint: "Air suspension fault, EPB warning.",                                 status: "In Progress",          assigned_technician: "Demo Tech 2", booked_in: "2026-04-22T09:30:00.000Z", estimated_completion: "2026-04-23T16:00:00.000Z", mileage: 71420, created_at: "2026-04-22T09:30:00.000Z", updated_at: "2026-04-22T15:00:00.000Z" },
  { id: "demo-job-011", job_number: "DEMO-1052", customer_id: "demo-cust-010", vehicle_id: "demo-veh-011", reg: "HP24 MOT", customer_name: "Rachel Hughes", make: "Vauxhall",   model: "Corsa",      complaint: "MOT only.",                                                          status: "MOT in progress",      assigned_technician: "Demo MOT",    booked_in: "2026-04-22T11:30:00.000Z", estimated_completion: "2026-04-22T12:30:00.000Z", mileage: 38940, created_at: "2026-04-22T11:30:00.000Z", updated_at: "2026-04-22T12:15:00.000Z" },
  { id: "demo-job-012", job_number: "DEMO-1053", customer_id: "demo-cust-011", vehicle_id: "demo-veh-012", reg: "WW24 ELC", customer_name: "David Khan",    make: "Volkswagen", model: "ID.4",       complaint: "Charge port fault.",                                                 status: "Awaiting Customer",    assigned_technician: "Demo Tech",   booked_in: "2026-04-20T16:00:00.000Z", estimated_completion: "2026-04-24T17:00:00.000Z", mileage: 12380, created_at: "2026-04-20T16:00:00.000Z", updated_at: "2026-04-22T11:00:00.000Z" },
];

const today = new Date().toISOString().slice(0, 10);
const yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString().slice(0, 10);

export const rows = rawRows.map((row, index) => {
  const numericId = 1042 + index;
  const isCarryOver = index % 4 === 1;
  const appointmentDate = isCarryOver ? yesterday : today;
  const appointmentTime = index % 3 === 0 ? "08:30" : index % 3 === 1 ? "10:00" : "13:30";
  const scheduledTime = `${appointmentDate}T${appointmentTime}:00.000Z`;
  const status = row.status === "Complete" || row.status === "Completed" ? "Complete" : row.status;
  const isMotJob = row.status?.toLowerCase().includes("mot") || row.complaint?.toLowerCase().includes("mot only");
  const technician = isMotJob
    ? { user_id: 1, first_name: "Demo", last_name: "MOT", email: "demo.mot@hnp.example", role: "mot tester" }
    : { user_id: 1, first_name: "Demo", last_name: "Tech", email: "demo.tech@hnp.example", role: "techs" };
  return {
    archived: false,
    is_active: true,
    deleted_at: null,
    org_id: null,
    tenant_id: null,
    completed_at: row.completed_at || null,
    ...row,
    id: numericId,
    status,
    raw_status: status,
    assigned_to: 1,
    job_source: index % 3 === 0 ? "Sales" : "Retail",
    job_division: index % 3 === 0 ? "Sales" : "Retail",
    job_categories: ["Service"],
    type: row.type || (isMotJob ? "MOT" : "Service"),
    description: row.description || row.complaint,
    completion_status: isMotJob ? "MOT pass" : index % 5 === 1 ? "Retest required" : index % 4 === 0 ? "Pass" : "Pending",
    tech_completion_status: index % 4 === 0 ? "complete" : "pending",
    checked_in_at: scheduledTime,
    service_mode: index % 3 === 0 ? "mobile" : "workshop",
    vehicle_reg: row.reg,
    vehicle_make_model: [row.make, row.model].filter(Boolean).join(" "),
    milage: row.mileage,
    booked_in: scheduledTime,
    created_at: scheduledTime,
    updated_at: scheduledTime,
    appointments: [
      {
        appointment_id: index + 1,
        job_id: numericId,
        scheduled_time: scheduledTime,
        status: "booked",
        notes: row.complaint || row.description || "",
        created_at: scheduledTime,
        updated_at: scheduledTime,
      },
    ],
    technician,
    vehicle: {
      vehicle_id: row.vehicle_id,
      registration: row.reg,
      reg_number: row.reg,
      make: row.make,
      model: row.model,
      make_model: [row.make, row.model].filter(Boolean).join(" "),
      mileage: row.mileage,
      customer: {
        id: row.customer_id,
        firstname: row.customer_name?.split(" ")[0] || "Demo",
        lastname: row.customer_name?.split(" ").slice(1).join(" ") || "Customer",
        email: `${String(row.customer_name || "customer").toLowerCase().replace(/\s+/g, ".")}@demo.invalid`,
        mobile: "07700 900000",
        telephone: "01392 555 000",
        address: "Demo address",
        postcode: "EX1 1AA",
        contact_preference: "email",
      },
    },
    job_requests: [
      {
        request_id: numericId,
        job_id: numericId,
        description: row.complaint || "Demo workshop request",
        hours: 1.5,
        job_type: "Customer",
        sort_order: 1,
        status: "pending",
        request_source: "customer_request",
        created_at: scheduledTime,
        updated_at: scheduledTime,
      },
    ],
    requests: [
      { id: `${numericId}-request`, text: row.complaint || "Demo workshop request", status: "pending" },
    ],
    vhc_checks: [
      {
        vhc_id: `${numericId}-vhc-1`,
        section: "Brakes",
        issue_title: "Front brake pads wearing low",
        issue_description: "Customer authorised replacement pads during the presentation walkthrough.",
        measurement: "3mm",
        severity: "amber",
        approval_status: "authorized",
        authorization_state: "authorized",
        display_status: "Authorized",
        labour_hours: 0.6,
        parts_cost: 54.2,
        created_at: scheduledTime,
        updated_at: scheduledTime,
      },
      {
        vhc_id: `${numericId}-vhc-2`,
        section: "Tyres",
        issue_title: "Nearside rear tyre advisory",
        issue_description: "Tread depth approaching advisory threshold.",
        measurement: "3.1mm",
        severity: "green",
        approval_status: "not_required",
        authorization_state: "not_required",
        display_status: "Recorded",
        labour_hours: 0,
        parts_cost: 0,
        created_at: scheduledTime,
        updated_at: scheduledTime,
      },
    ],
    parts_requests: [
      {
        request_id: `${numericId}-part-request`,
        part_id: "demo-part-001",
        quantity: 1,
        status: "on_order",
        requested_by: 1,
        approved_by: 1,
        pre_pick_location: "Workshop bay 2",
        created_at: scheduledTime,
        updated_at: scheduledTime,
      },
    ],
    parts_job_items: [
      {
        id: `${numericId}-part-item`,
        part_id: "demo-part-001",
        authorised: true,
        quantity_requested: 1,
        quantity_allocated: 1,
        quantity_fitted: 0,
        allocated_to_request_id: `${numericId}-part-request`,
        status: "allocated",
        origin: "presentation",
        pre_pick_location: "Workshop bay 2",
        storage_location: "A1-03",
        unit_cost: 31.5,
        unit_price: 54.2,
        request_notes: "Demo stock allocated",
        allocated_by: 1,
        created_at: scheduledTime,
        updated_at: scheduledTime,
        part: {
          id: "demo-part-001",
          part_number: "HNP-BPAD-01",
          name: "Front brake pad set",
          description: "Presentation brake pad stock",
          unit_cost: 31.5,
          unit_price: 54.2,
          qty_in_stock: 8,
          qty_reserved: 1,
          qty_on_order: 4,
          storage_location: "A1-03",
        },
      },
    ],
    goods_in_items: [
      {
        id: `${numericId}-goods-item`,
        goods_in_id: "demo-gi-001",
        job_id: numericId,
        job_number: row.job_number,
        part_number: "HNP-BPAD-01",
        description: "Front brake pad set",
        quantity: 1,
        cost_price: 31.5,
        retail_price: 54.2,
        bin_location: "A1-03",
        surcharge: "",
        added_to_job: true,
        created_at: scheduledTime,
        updated_at: scheduledTime,
        goods_in: {
          goods_in_number: "GI-5001",
          supplier_name: "VAG Parts",
          invoice_number: "INV-GI-5001",
        },
      },
    ],
  };
});
