const today = new Date().toISOString().slice(0, 10);

const rawRows = [
  { id: "demo-gi-001", goods_in_number: "GI-5001", order_number: "PO-3002", supplier: "Ford Direct", received_by: "Demo Parts", received_at: `${today}T10:18:00.000Z`, status: "Booked In", line_count: 2 },
  { id: "demo-gi-002", goods_in_number: "GI-5002", order_number: "PO-3003", supplier: "Euro Car Parts", received_by: "Demo Parts", received_at: `${today}T11:02:00.000Z`, status: "Booked In", line_count: 2 },
  { id: "demo-gi-003", goods_in_number: "GI-5003", order_number: "PO-2999", supplier: "VAG Parts", received_by: "Demo Parts", received_at: `${today}T07:40:00.000Z`, status: "Discrepancy", line_count: 3 },
  { id: "demo-gi-004", goods_in_number: "GI-5004", order_number: "PO-3008", supplier: "BMW Parts", received_by: "Demo Parts", received_at: `${today}T07:30:00.000Z`, status: "Booked In", line_count: 1 },
  { id: "demo-gi-005", goods_in_number: "GI-5005", order_number: "PO-3007", supplier: "Tyre Wholesale", received_by: "Demo Parts", received_at: `${today}T14:35:00.000Z`, status: "Pending QC", line_count: 1 },
  { id: "demo-gi-006", goods_in_number: "GI-5006", order_number: "PO-2998", supplier: "Honda Direct", received_by: "Demo Parts", received_at: `${today}T15:55:00.000Z`, status: "Booked In", line_count: 4 },
];

export const rows = rawRows.map((row) => ({
  archived: false,
  is_active: true,
  deleted_at: null,
  org_id: null,
  tenant_id: null,
  supplier_name: row.supplier,
  supplier_account_id: null,
  supplier_address: "Demo supplier address",
  supplier_contact: row.supplier,
  invoice_number: `INV-${row.goods_in_number}`,
  delivery_note_number: row.order_number,
  invoice_date: row.received_at.slice(0, 10),
  price_level: "stock_order_rate",
  notes: "",
  scan_payload: {},
  created_at: row.received_at,
  updated_at: row.received_at,
  completed_at: row.status === "Booked In" ? row.received_at : null,
  items: [
    {
      id: `${row.id}-job-item`,
      goods_in_id: row.id,
      job_id: 1042,
      job_number: "DEMO-1042",
      part_number: "HNP-BPAD-01",
      description: "Front brake pad set",
      quantity: 1,
      cost_price: 31.5,
      retail_price: 54.2,
      bin_location: "A1-03",
      added_to_job: true,
      destination: "job",
      created_at: row.received_at,
      updated_at: row.received_at,
    },
    {
      id: `${row.id}-stock-item`,
      goods_in_id: row.id,
      job_id: null,
      job_number: null,
      part_number: "HNP-FILT-02",
      description: "Service filter kit",
      quantity: 2,
      cost_price: 12.4,
      retail_price: 22,
      bin_location: "B2-01",
      added_to_job: false,
      destination: "stock",
      created_at: row.received_at,
      updated_at: row.received_at,
    },
  ],
  ...row,
}));
