// Presentation mock rows for the public /website shop and the staff
// Website Manager shop panel. Shape mirrors the shop_* Supabase tables.

const now = "2026-05-21T09:00:00.000Z";

export const categories = [
  {
    id: "suzuki-service",
    slug: "suzuki-service",
    name: "Suzuki Service",
    description: "Service kits and care items for Suzuki customers.",
    sort_order: 10,
    status: "active",
    updated_at: now,
    updated_by: "Presentation",
  },
  {
    id: "kgm-accessories",
    slug: "kgm-accessories",
    name: "KGM Accessories",
    description: "Tow bars, mats and touring accessories.",
    sort_order: 20,
    status: "active",
    updated_at: now,
    updated_by: "Presentation",
  },
  {
    id: "cleaning-care",
    slug: "cleaning-care",
    name: "Cleaning & Care",
    description: "Dealer-approved cleaning and winter care packs.",
    sort_order: 30,
    status: "active",
    updated_at: now,
    updated_by: "Presentation",
  },
];

export const products = [
  {
    id: "swift-service-kit",
    category_id: "suzuki-service",
    sku: "HNP-SWIFT-SVC",
    name: "Suzuki Swift service kit",
    slug: "suzuki-swift-service-kit",
    description: "Oil filter, air filter and sump washer for current Swift models.",
    price_pence: 5495,
    compare_at_price_pence: 6295,
    image_url: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=900&q=80",
    gallery: [],
    stock_qty: 12,
    fit_brands: ["Suzuki"],
    status: "published",
    sort_order: 10,
    created_at: now,
    updated_at: now,
    updated_by: "Presentation",
  },
  {
    id: "vitara-boot-liner",
    category_id: "kgm-accessories",
    sku: "HNP-VIT-LINER",
    name: "All-weather boot liner",
    slug: "all-weather-boot-liner",
    description: "Heavy-duty protective boot liner for family cars and crossovers.",
    price_pence: 7995,
    compare_at_price_pence: null,
    image_url: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=900&q=80",
    gallery: [],
    stock_qty: 4,
    fit_brands: ["Suzuki", "KGM", "Mitsubishi"],
    status: "published",
    sort_order: 20,
    created_at: now,
    updated_at: now,
    updated_by: "Presentation",
  },
  {
    id: "winter-care-pack",
    category_id: "cleaning-care",
    sku: "HNP-WINTER-CARE",
    name: "Winter care pack",
    slug: "winter-care-pack",
    description: "Screenwash, de-icer, scraper and microfibre cloths.",
    price_pence: 2495,
    compare_at_price_pence: 2995,
    image_url: "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?auto=format&fit=crop&w=900&q=80",
    gallery: [],
    stock_qty: 18,
    fit_brands: ["Suzuki", "KGM", "Mitsubishi"],
    status: "published",
    sort_order: 30,
    created_at: now,
    updated_at: now,
    updated_by: "Presentation",
  },
];

export const orders = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    order_number: "HNP-2026-DEMO01",
    customer_id: null,
    contact_email: "customer.demo@example.com",
    contact_phone: "01732 870711",
    shipping_address: {
      name: "Demo Customer",
      line1: "120 London Road",
      city: "West Malling",
      postcode: "ME19 5AN",
      country: "United Kingdom",
    },
    status: "paid",
    subtotal_pence: 10490,
    shipping_pence: 595,
    tax_pence: 0,
    total_pence: 11085,
    currency: "GBP",
    stripe_session_id: "cs_test_presentation",
    stripe_payment_intent: "pi_presentation",
    notes: "Presentation order for the public website shop.",
    created_at: now,
    updated_at: now,
    updated_by: "Presentation",
    items: [
      {
        id: 1,
        order_id: "11111111-1111-4111-8111-111111111111",
        product_id: "swift-service-kit",
        sku: "HNP-SWIFT-SVC",
        name: "Suzuki Swift service kit",
        qty: 1,
        unit_price_pence: 5495,
        line_total_pence: 5495,
      },
      {
        id: 2,
        order_id: "11111111-1111-4111-8111-111111111111",
        product_id: "winter-care-pack",
        sku: "HNP-WINTER-CARE",
        name: "Winter care pack",
        qty: 2,
        unit_price_pence: 2495,
        line_total_pence: 4990,
      },
    ],
  },
];
