// file location: src/lib/hr/mockData.js

export const hrDashboardMetrics = [
  {
    id: "totalEmployees",
    label: "Total Employees",
    icon: "👥",
    active: 86,
    inactive: 7,
  },
  {
    id: "attendanceRate",
    label: "Attendance Rate",
    icon: "🕒",
    value: "94%",
    trend: "+3% vs last week",
  },
  {
    id: "performanceScore",
    label: "Performance Score",
    icon: "📈",
    value: "4.2 / 5",
    trend: "+0.2 vs last month",
  },
  {
    id: "trainingCompliance",
    label: "Training Compliance",
    icon: "🎓",
    value: "88%",
    trend: "-4% vs target",
  },
];

export const upcomingAbsences = [
  {
    id: 1,
    employee: "Sarah Thompson",
    department: "Workshop",
    type: "Annual Leave",
    startDate: "2024-03-18",
    endDate: "2024-03-22",
  },
  {
    id: 2,
    employee: "Lewis Carter",
    department: "Service",
    type: "Sick Leave",
    startDate: "2024-03-14",
    endDate: "2024-03-15",
  },
  {
    id: 3,
    employee: "Maya Patel",
    department: "Sales",
    type: "Training",
    startDate: "2024-03-19",
    endDate: "2024-03-19",
  },
];

export const activeWarnings = [
  {
    id: 1,
    employee: "Aaron Blake",
    department: "Workshop",
    level: "Written Warning",
    issuedOn: "2024-02-02",
    notes: "Repeated late arrivals.",
  },
  {
    id: 2,
    employee: "Emily Chen",
    department: "Service",
    level: "Verbal Warning",
    issuedOn: "2024-02-26",
    notes: "Missing paperwork on job handovers.",
  },
];

export const departmentPerformance = [
  {
    id: "workshop",
    department: "Workshop",
    productivity: 92,
    quality: 88,
    teamwork: 90,
  },
  {
    id: "service",
    department: "Service",
    productivity: 84,
    quality: 81,
    teamwork: 86,
  },
  {
    id: "sales",
    department: "Sales",
    productivity: 78,
    quality: 89,
    teamwork: 83,
  },
];

export const trainingRenewals = [
  {
    id: 1,
    course: "Hybrid Vehicle Safety",
    employee: "Claire Murphy",
    dueDate: "2024-04-12",
    status: "Due Soon",
  },
  {
    id: 2,
    course: "MOT Tester Certification",
    employee: "Daniel Reyes",
    dueDate: "2024-03-30",
    status: "Overdue",
  },
  {
    id: 3,
    course: "Customer Care Essentials",
    employee: "Alex Johnson",
    dueDate: "2024-04-05",
    status: "Scheduled",
  },
];

export const employeeDirectory = [
  {
    id: "EMP-1024",
    name: "Sarah Thompson",
    jobTitle: "Workshop Manager",
    department: "Workshop",
    role: "Workshop Manager",
    employmentType: "Full-time",
    startDate: "2020-07-01",
    probationEnd: "2020-12-31",
    status: "Active",
    email: "sarah.thompson@example.com",
    phone: "+44 7543 123456",
    emergencyContact: "Luke Thompson (+44 7700 900123)",
    address: "12 Meadow Park, Leeds, LS1 3AB",
    contractedHours: 40,
    hourlyRate: 28.5,
    keycloakId: "kc-sarah",
    documents: [
      { id: "DOC-1", name: "Employment Contract", type: "contract", uploadedOn: "2020-07-01" },
      { id: "DOC-2", name: "Driving Licence", type: "licence", uploadedOn: "2023-01-10" },
      { id: "DOC-3", name: "Hybrid Vehicle Certificate", type: "training", uploadedOn: "2023-11-30" },
    ],
  },
  {
    id: "EMP-1120",
    name: "Michael Green",
    jobTitle: "Senior Technician",
    department: "Workshop",
    role: "Tech",
    employmentType: "Full-time",
    startDate: "2019-04-18",
    probationEnd: "2019-10-18",
    status: "Active",
    email: "michael.green@example.com",
    phone: "+44 7567 890321",
    emergencyContact: "Hannah Green (+44 7700 900456)",
    address: "18 Oak Lane, Leeds, LS7 2RF",
    contractedHours: 38,
    hourlyRate: 22.1,
    keycloakId: "kc-michael",
    documents: [
      { id: "DOC-4", name: "Employment Contract", type: "contract", uploadedOn: "2019-04-18" },
      { id: "DOC-5", name: "MOT Certification", type: "certificate", uploadedOn: "2022-05-01" },
    ],
  },
  {
    id: "EMP-1188",
    name: "Lewis Carter",
    jobTitle: "Service Manager",
    department: "Service",
    role: "Service Manager",
    employmentType: "Full-time",
    startDate: "2018-09-03",
    probationEnd: "2019-03-03",
    status: "Active",
    email: "lewis.carter@example.com",
    phone: "+44 7712 555210",
    emergencyContact: "Laura Carter (+44 7700 900789)",
    address: "34 Riverbank Way, Leeds, LS2 8PP",
    contractedHours: 40,
    hourlyRate: 26.0,
    keycloakId: "kc-lewis",
    documents: [
      { id: "DOC-6", name: "Employment Contract", type: "contract", uploadedOn: "2018-09-03" },
      { id: "DOC-7", name: "Customer Care Diploma", type: "training", uploadedOn: "2021-04-15" },
    ],
  },
  {
    id: "EMP-1255",
    name: "Amelia Wright",
    jobTitle: "Sales Executive",
    department: "Sales",
    role: "Sales",
    employmentType: "Full-time",
    startDate: "2021-01-11",
    probationEnd: "2021-07-11",
    status: "On leave",
    email: "amelia.wright@example.com",
    phone: "+44 7765 441298",
    emergencyContact: "James Wright (+44 7700 903212)",
    address: "27 Elm Close, Bradford, BD4 7HQ",
    contractedHours: 37,
    hourlyRate: 20.5,
    keycloakId: "kc-amelia",
    documents: [
      { id: "DOC-8", name: "Sales Contract", type: "contract", uploadedOn: "2021-01-11" },
      { id: "DOC-9", name: "FCA Compliance Certificate", type: "training", uploadedOn: "2023-06-08" },
    ],
  },
  {
    id: "EMP-1310",
    name: "Daniel Reyes",
    jobTitle: "MOT Tester",
    department: "Workshop",
    role: "MOT Tester",
    employmentType: "Full-time",
    startDate: "2022-05-16",
    probationEnd: "2022-11-16",
    status: "Active",
    email: "daniel.reyes@example.com",
    phone: "+44 7799 213654",
    emergencyContact: "Claudia Reyes (+44 7700 906543)",
    address: "5 Beacon Court, Wakefield, WF1 9DX",
    contractedHours: 38,
    hourlyRate: 23.4,
    keycloakId: "kc-daniel",
    documents: [
      { id: "DOC-10", name: "MOT Tester Licence", type: "certificate", uploadedOn: "2023-02-19" },
      { id: "DOC-11", name: "Safety Refresher", type: "training", uploadedOn: "2023-10-02" },
    ],
  },
  {
    id: "EMP-1399",
    name: "Olivia Baker",
    jobTitle: "HR Coordinator",
    department: "Admin",
    role: "HR",
    employmentType: "Part-time",
    startDate: "2020-03-02",
    probationEnd: "2020-09-02",
    status: "Active",
    email: "olivia.baker@example.com",
    phone: "+44 7701 555901",
    emergencyContact: "Tom Baker (+44 7700 908812)",
    address: "14 Chapel Rise, Harrogate, HG1 5QT",
    contractedHours: 28,
    hourlyRate: 19.75,
    keycloakId: "kc-olivia",
    documents: [
      { id: "DOC-12", name: "Employment Contract", type: "contract", uploadedOn: "2020-03-02" },
      { id: "DOC-13", name: "CIPD Level 5", type: "certificate", uploadedOn: "2022-09-14" },
    ],
  },
  {
    id: "EMP-1424",
    name: "Kai Patel",
    jobTitle: "Valet Supervisor",
    department: "Valet",
    role: "Valet",
    employmentType: "Full-time",
    startDate: "2017-11-20",
    probationEnd: "2018-05-20",
    status: "Active",
    email: "kai.patel@example.com",
    phone: "+44 7720 441177",
    emergencyContact: "Priya Patel (+44 7700 907654)",
    address: "48 Sandstone Lane, Leeds, LS10 3TR",
    contractedHours: 39,
    hourlyRate: 18.0,
    keycloakId: "kc-kai",
    documents: [
      { id: "DOC-14", name: "Supervisor Contract", type: "contract", uploadedOn: "2017-11-20" },
      { id: "DOC-15", name: "COSHH Training", type: "training", uploadedOn: "2023-08-22" },
    ],
  },
  {
    id: "EMP-1466",
    name: "Jade Murphy",
    jobTitle: "Parts Advisor",
    department: "Parts",
    role: "Parts",
    employmentType: "Full-time",
    startDate: "2023-04-04",
    probationEnd: "2023-10-04",
    status: "Active",
    email: "jade.murphy@example.com",
    phone: "+44 7755 667731",
    emergencyContact: "Patrick Murphy (+44 7700 902211)",
    address: "62 Millstone Drive, York, YO1 6PR",
    contractedHours: 37,
    hourlyRate: 17.8,
    keycloakId: "kc-jade",
    documents: [
      { id: "DOC-16", name: "Employment Contract", type: "contract", uploadedOn: "2023-04-04" },
      { id: "DOC-17", name: "Stock Control Certificate", type: "training", uploadedOn: "2023-09-01" },
    ],
  },
];

export const attendanceLogs = [
  {
    id: "ATT-1",
    employeeId: "EMP-1120",
    date: "2024-03-11",
    clockIn: "08:02",
    clockOut: "17:05",
    totalHours: 8.5,
    status: "On Time",
  },
  {
    id: "ATT-2",
    employeeId: "EMP-1024",
    date: "2024-03-11",
    clockIn: "07:55",
    clockOut: "17:20",
    totalHours: 9.1,
    status: "Overtime",
  },
];

export const absenceRecords = [
  {
    id: "ABS-1",
    employeeId: "EMP-1202",
    employee: "Rachel Park",
    type: "Annual Leave",
    startDate: "2024-03-14",
    endDate: "2024-03-18",
    approvalStatus: "Approved",
  },
  {
    id: "ABS-2",
    employeeId: "EMP-1114",
    employee: "Josh Edwards",
    type: "Sick Leave",
    startDate: "2024-03-12",
    endDate: "2024-03-13",
    approvalStatus: "Pending",
  },
];

export const overtimeSummaries = [
  {
    id: "OT-1",
    employeeId: "EMP-1120",
    employee: "Michael Green",
    periodStart: "2024-02-26",
    periodEnd: "2024-03-25",
    overtimeHours: 12.5,
    overtimeRate: 33.15,
    bonus: 150,
    status: "Ready",
  },
  {
    id: "OT-2",
    employeeId: "EMP-1268",
    employee: "Katie Lewis",
    periodStart: "2024-02-26",
    periodEnd: "2024-03-25",
    overtimeHours: 6,
    overtimeRate: 29.5,
    bonus: 0,
    status: "Pending Approval",
  },
];

export const payRateHistory = [
  {
    id: "PAY-1",
    employeeId: "EMP-1120",
    effectiveDate: "2024-01-01",
    rate: 22.1,
    type: "Hourly",
    approvedBy: "Sarah Thompson",
  },
  {
    id: "PAY-2",
    employeeId: "EMP-1120",
    effectiveDate: "2023-06-01",
    rate: 20.5,
    type: "Hourly",
    approvedBy: "Sarah Thompson",
  },
];

export const leaveRequests = [
  {
    id: "LR-1",
    employeeId: "EMP-1202",
    employee: "Rachel Park",
    type: "Annual Leave",
    startDate: "2024-04-02",
    endDate: "2024-04-05",
    status: "Pending",
    submittedOn: "2024-03-10",
    approver: "Lewis Carter",
  },
  {
    id: "LR-2",
    employeeId: "EMP-1098",
    employee: "James Martin",
    type: "Sick Leave",
    startDate: "2024-03-09",
    endDate: "2024-03-11",
    status: "Approved",
    submittedOn: "2024-03-09",
    approver: "Sarah Thompson",
  },
  {
    id: "LR-3",
    employeeId: "EMP-1155",
    employee: "Olivia Baker",
    type: "Maternity Leave",
    startDate: "2024-05-01",
    endDate: "2024-09-30",
    status: "Scheduled",
    submittedOn: "2024-02-20",
    approver: "HR Team",
  },
];

export const leaveBalances = [
  {
    employeeId: "EMP-1202",
    employee: "Rachel Park",
    department: "Service",
    entitlement: 25,
    taken: 6,
    remaining: 19,
  },
  {
    employeeId: "EMP-1098",
    employee: "James Martin",
    department: "Workshop",
    entitlement: 28,
    taken: 12,
    remaining: 16,
  },
];
