-- // file location: src/lib/database/schema/addtable.sql
-- // description: defines supplemental tables added beyond reference schema

CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid,
  customer_id uuid,
  total_parts numeric DEFAULT 0,
  total_labour numeric DEFAULT 0,
  total_vat numeric DEFAULT 0,
  total numeric DEFAULT 0,
  paid boolean NOT NULL DEFAULT false,
  payment_method text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  sent_email_at timestamp with time zone,
  sent_portal_at timestamp with time zone,
  CONSTRAINT invoices_pkey PRIMARY KEY (id)
);

CREATE TABLE public.invoice_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL,
  description text NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  CONSTRAINT invoice_items_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);

CREATE TABLE public.payment_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL,
  provider text NOT NULL,
  checkout_url text NOT NULL,
  expires_at timestamp with time zone,
  CONSTRAINT payment_links_pkey PRIMARY KEY (id),
  CONSTRAINT payment_links_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);

CREATE TABLE public.job_booking_requests (
  request_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id integer NOT NULL REFERENCES public.jobs(id),
  customer_id uuid REFERENCES public.customers(id),
  vehicle_id integer REFERENCES public.vehicles(vehicle_id),
  description text NOT NULL,
  waiting_status text,
  status text NOT NULL DEFAULT 'pending',
  submitted_by integer REFERENCES public.users(user_id),
  submitted_by_name text,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  approved_by integer REFERENCES public.users(user_id),
  approved_by_name text,
  approved_at timestamp with time zone,
  confirmation_sent_at timestamp with time zone,
  price_estimate numeric,
  estimated_completion timestamp with time zone,
  loan_car_details text,
  confirmation_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT job_booking_requests_job_id_key UNIQUE (job_id)
);

CREATE TABLE public.customer_payment_methods (
  method_id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL REFERENCES public.customers(id),
  nickname text,
  card_brand text,
  last4 text NOT NULL,
  expiry_month integer NOT NULL,
  expiry_year integer NOT NULL,
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customer_payment_methods_pkey PRIMARY KEY (method_id)
);

CREATE TABLE public.payment_plans (
  plan_id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL REFERENCES public.customers(id),
  job_id integer REFERENCES public.jobs(id),
  invoice_id uuid REFERENCES public.invoices(id),
  name text,
  description text,
  total_amount numeric NOT NULL DEFAULT 0,
  balance_due numeric NOT NULL DEFAULT 0,
  frequency text,
  next_payment_date date,
  status text NOT NULL DEFAULT 'active',
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_plans_pkey PRIMARY KEY (plan_id)
);

CREATE TABLE public.staff_vehicles (
  vehicle_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id integer NOT NULL REFERENCES public.users(user_id),
  make text,
  model text,
  registration text NOT NULL,
  vin text,
  colour text,
  payroll_deduction_enabled boolean NOT NULL DEFAULT true,
  payroll_deduction_reference text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT staff_vehicles_pkey PRIMARY KEY (vehicle_id)
);

CREATE TABLE public.staff_vehicle_history (
  history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id uuid NOT NULL REFERENCES public.staff_vehicles(vehicle_id) ON DELETE CASCADE,
  job_id integer REFERENCES public.jobs(id),
  description text,
  cost numeric DEFAULT 0,
  deduct_from_payroll boolean NOT NULL DEFAULT true,
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  payroll_processed_at timestamp with time zone
);
