-- Global floating notes for per-user and dev-shared notes widget
CREATE TABLE IF NOT EXISTS public.floating_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  title text NOT NULL DEFAULT 'New note',
  description text NOT NULL DEFAULT '',
  is_global boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT floating_notes_title_length_check CHECK (char_length(title) <= 200)
);

ALTER TABLE public.floating_notes
  ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.floating_notes
  ADD COLUMN IF NOT EXISTS is_global boolean NOT NULL DEFAULT false;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'floating_notes'
      AND column_name = 'shared_all_users'
  ) THEN
    EXECUTE 'UPDATE public.floating_notes
             SET is_global = COALESCE(shared_all_users, false)
             WHERE is_global IS DISTINCT FROM COALESCE(shared_all_users, false)';
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_floating_notes_user_id ON public.floating_notes(user_id);
CREATE INDEX IF NOT EXISTS idx_floating_notes_is_global ON public.floating_notes(is_global);

CREATE OR REPLACE FUNCTION public.set_floating_notes_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_floating_notes_updated_at ON public.floating_notes;
CREATE TRIGGER trg_floating_notes_updated_at
BEFORE UPDATE ON public.floating_notes
FOR EACH ROW
EXECUTE FUNCTION public.set_floating_notes_updated_at();
