-- // file location: src/lib/database/schema/addtable.sql
-- // description: defines supplemental tables added beyond reference schema

-- added
CREATE TABLE public.job_requests ( -- // stores each job request as its own row
  request_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- // surrogate primary key for job requests
  job_id integer NOT NULL REFERENCES public.jobs(id), -- // foreign key linking to jobs table
  description text NOT NULL, -- // details of the work requested
  hours numeric(6,2), -- // estimated labour hours for the request
  job_type text NOT NULL DEFAULT 'Customer', -- // billing type such as customer or warranty
  sort_order integer NOT NULL DEFAULT 1, -- // preserves order of requests entered on the form
  created_at timestamp with time zone NOT NULL DEFAULT now(), -- // creation timestamp
  updated_at timestamp with time zone NOT NULL DEFAULT now() -- // last update timestamp
); -- // end job_requests definition
-- ^^^^^