export const departmentDashboardShortcuts = [
  {
    label: "Retail Dashboard",
    href: "/dashboard",
    roles: [
      "service",
      "service department",
      "service advisor",
      "service manager",
      "workshop manager",
      "after sales director",
    ],
    description: "Live retail and service overview",
  },
  {
    label: "Workshop Dashboard",
    href: "/dashboard/workshop",
    roles: ["workshop manager", "techs", "technician"],
    description: "Technician assignments, consumables, and throughput",
  },
  {
    label: "Tech Dashboard",
    href: "/tech/dashboard",
    roles: ["techs"],
    description: "Technician personal dashboard with job assignments and clocking",
  },
  {
    label: "Mobile Tech Dashboard",
    href: "/mobile/dashboard",
    roles: ["mobile technician"],
    description: "Today's on-site jobs, appointment windows, and parts status for mobile visits",
  },
  {
    label: "Service Dashboard",
    href: "/dashboard/service",
    roles: ["service", "service manager"],
    description: "Advisor capacity, arrivals, and daily targets",
  },
  {
    label: "Managers Dashboard",
    href: "/dashboard/managers",
    roles: [
      "service manager",
      "workshop manager",
      "parts manager",
      "admin manager",
      "accounts manager",
      "general manager",
      "owner",
    ],
    description: "Executive view for service, workshop, and support leaders",
  },
  {
    label: "Parts Dashboard",
    href: "/dashboard/parts",
    roles: ["parts", "parts manager"],
    description: "Parts queue, inbound deliveries, and critical items",
  },
  {
    label: "Parts Manager Dashboard",
    href: "/parts/manager",
    roles: ["parts manager"],
    description: "View stock, spending, and income KPIs",
  },
  {
    label: "MOT Dashboard",
    href: "/dashboard/mot",
    roles: ["mot tester"],
    description: "Upcoming MOT bookings, re-tests, and compliance notes",
  },
  {
    label: "Valeting Dashboard",
    href: "/dashboard/valeting",
    roles: ["valet service"],
    description: "Wash bay priorities, handovers, and staff load",
  },
  {
    label: "Painting Dashboard",
    href: "/dashboard/painting",
    roles: ["painters"],
    description: "Bodyshop priorities, colour matching, and cycle times",
  },
  {
    label: "Accounts Dashboard",
    href: "/dashboard/accounts",
    roles: ["accounts", "accounts manager"],
    description: "Financial KPIs, invoices, and cash-flow signals",
  },
  {
    label: "Admin Dashboard",
    href: "/dashboard/admin",
    roles: ["admin", "admin manager"],
    description: "Admin alerts, approvals, and escalation flags",
  },
];
