// src/config/users.js
export const usersByRole = {
  Admin: ["Alisha", "Zedenca"],
  "Admin Manager": ["Julie"],
  Accounts: ["Ally"],
  "Accounts Manager": ["Paul"],
  Owner: ["Marcus"],
  "General Manager": ["Owen"],
  "Sales Director": ["Sam"],
  Sales: ["Josh", "Brad", "Richard", "Rob"],
  Service: ["Nicola", "Sharna"],
  "Service Manager": ["Darrell"],
  "Workshop Manager": ["Darrell"],
  "After Sales Director": ["Soren"],
  Techs: ["Glen", "Michael", "Jake", "Scott", "Paul", "Cheryl"],
  Parts: ["Alister"],
  "Parts Manager": ["Scott"],
  "MOT Tester": ["Russel", "Jake (tech) - when Russel off"],
  "Valet Service": ["Paul"],
  "Valet Sales": ["Alex", "Harvey", "Peter"],
  "Buying Director": ["Bruno"],
  "Second Hand Buying": ["Sophie"],
  "Vehicle Processor & Photographer": ["Grace"],
  Receptionist: ["Carol"],
  Painters: ["Guy 1", "Guy 2"],
  Contractors: ["Smart Repair", "Paints (grey van)", "Dent Man", "Wheel Men", "Windscreen Guy", "Key Guy"],
};

// Map retail vs sales departments to provide grouped developer login options
export const roleCategories = {
  Retail: [
    "Admin",
    "Admin Manager",
    "Accounts",
    "Accounts Manager",
    "Owner",
    "General Manager",
    "Service",
    "Service Manager",
    "Workshop Manager",
    "After Sales Director",
    "Techs",
    "Parts",
    "Parts Manager",
    "MOT Tester",
    "Valet Service",
    "Receptionist",
    "Painters",
    "Contractors",
  ],
  Sales: [
    "Sales Director",
    "Sales",
    "Valet Sales",
    "Buying Director",
    "Second Hand Buying",
    "Vehicle Processor & Photographer",
  ],
};
