export const demoVehicles = [
  {
    id: "demo-veh-001",
    customer_id: "demo-cust-001",
    reg: "DE24 XYZ",
    make: "Volkswagen",
    model: "Golf",
    year: 2022,
    vin: "WVWZZZ1KZDEMO0001",
    mot_expiry: "2026-08-14",
    colour: "Deep Black Pearl",
  },
  {
    id: "demo-veh-002",
    customer_id: "demo-cust-002",
    reg: "TA23 ABC",
    make: "Ford",
    model: "Kuga",
    year: 2023,
    vin: "WF0ZZZKUGADEMO002",
    mot_expiry: "2026-11-30",
    colour: "Magnetic Grey",
  },
  {
    id: "demo-veh-003",
    customer_id: "demo-cust-003",
    reg: "TV22 HNP",
    make: "BMW",
    model: "3 Series",
    year: 2022,
    vin: "WBA3DEMOBMWDEMO03",
    mot_expiry: "2027-01-12",
    colour: "Alpine White",
  },
];
