// file location: src/lib/tracking/mockEntries.js

export const initialTrackingEntries = [
  {
    id: "track-1001",
    jobNumber: "HNP-4821",
    reg: "GY21 HNP",
    customer: "Emma Lane",
    serviceType: "Major Service",
    status: "Waiting For Collection",
    parkedBy: "Tom Jackson",
    parkedAt: "09:45",
    updatedAt: "2024-05-06T09:45:00.000Z",
    vehicleLocation: "Front Row – Bay A",
    keyLocation: "Key Safe A – Hooks 1-10",
    keyTip: "Green tag #4",
    notes: "Customer collecting at 16:00",
  },
  {
    id: "track-1002",
    jobNumber: "HNP-4610",
    reg: "AB70 RFT",
    customer: "Caleb Howard",
    serviceType: "Warranty Repair",
    status: "Awaiting Authorization",
    parkedBy: "Maya Patel",
    parkedAt: "10:12",
    updatedAt: "2024-05-06T10:12:00.000Z",
    vehicleLocation: "Overflow – West Fence",
    keyLocation: "Key Safe B – Hooks 11-20",
    keyTip: "Yellow tag #12",
    notes: "Awaiting callback from customer",
  },
  {
    id: "track-1003",
    jobNumber: "HNP-4598",
    reg: "PX22 VHC",
    customer: "Gemma Price",
    serviceType: "Valet",
    status: "Valet Hold",
    parkedBy: "Valet Team",
    parkedAt: "11:05",
    updatedAt: "2024-05-06T11:05:00.000Z",
    vehicleLocation: "Valet Lane",
    keyLocation: "Valet Pouch Rack",
    keyTip: "Pouch slot 3",
    notes: "Interior detail in progress",
  },
  {
    id: "track-1004",
    jobNumber: "HNP-4580",
    reg: "HJ19 FBC",
    customer: "Zac Morgan",
    serviceType: "MOT & Service",
    status: "Ready For Collection",
    parkedBy: "Service Team",
    parkedAt: "08:55",
    updatedAt: "2024-05-06T08:55:00.000Z",
    vehicleLocation: "Handover Suite",
    keyLocation: "Service Desk Drawer",
    keyTip: "Drawer slot 2",
    notes: "Customer waiting with adviser",
  },
];
