begin;

create extension if not exists pgcrypto;

create table if not exists public.audit_sessions (
  id uuid primary key default gen_random_uuid(),
  client_session_id uuid not null,
  user_id integer not null references public.users(user_id) on delete restrict,
  user_name text not null,
  user_email text,
  role text,
  department text,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  last_activity_at timestamptz not null default now(),
  duration_seconds integer,
  end_reason text,
  status text not null default 'active'
    check (status in ('active', 'logged_out', 'timed_out', 'expired', 'unexpected_close')),
  ip_address inet,
  device_category text
    check (device_category is null or device_category in ('desktop', 'laptop', 'tablet', 'mobile')),
  operating_system text,
  browser_name text,
  browser_version text,
  app_mode text
    check (app_mode is null or app_mode in ('browser', 'pwa', 'installed_app')),
  user_agent text,
  created_at timestamptz not null default now(),
  unique (user_id, client_session_id)
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  session_id uuid references public.audit_sessions(id) on delete restrict,
  actor_user_id integer references public.users(user_id) on delete restrict,
  actor_name text,
  actor_role text,
  actor_department text,
  occurred_at timestamptz not null default now(),
  event_name text not null,
  action_category text not null,
  feature text,
  route text,
  page_title text,
  previous_page text,
  page_entered_at timestamptz,
  page_left_at timestamptz,
  duration_ms integer,
  action_label text,
  record_type text,
  record_id text,
  outcome text not null default 'success'
    check (outcome in ('success', 'failure', 'cancelled', 'unknown')),
  request_id uuid,
  dedupe_key text,
  before_data jsonb,
  after_data jsonb,
  metadata jsonb not null default '{}'::jsonb,
  ip_address inet,
  prev_hash text,
  row_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_events_archive (
  archive_id bigint generated by default as identity primary key,
  original_event_id bigint not null unique,
  session_id uuid,
  actor_user_id integer,
  actor_name text,
  actor_role text,
  actor_department text,
  occurred_at timestamptz not null,
  event_name text not null,
  action_category text not null,
  feature text,
  route text,
  page_title text,
  previous_page text,
  page_entered_at timestamptz,
  page_left_at timestamptz,
  duration_ms integer,
  action_label text,
  record_type text,
  record_id text,
  outcome text not null,
  request_id uuid,
  dedupe_key text,
  before_data jsonb,
  after_data jsonb,
  metadata jsonb not null default '{}'::jsonb,
  ip_address inet,
  prev_hash text,
  row_hash text not null,
  created_at timestamptz not null,
  archived_at timestamptz not null default now()
);

create table if not exists public.audit_retention_settings (
  id smallint primary key default 1 check (id = 1),
  live_days integer not null default 365 check (live_days between 30 and 3650),
  archive_days integer not null default 2555 check (archive_days between 365 and 7300),
  session_timeout_minutes integer not null default 30
    check (session_timeout_minutes between 5 and 1440),
  updated_at timestamptz not null default now(),
  updated_by integer references public.users(user_id) on delete set null
);

insert into public.audit_retention_settings (id)
values (1)
on conflict (id) do nothing;

create index if not exists audit_sessions_user_started_idx
  on public.audit_sessions (user_id, started_at desc);
create index if not exists audit_sessions_status_activity_idx
  on public.audit_sessions (status, last_activity_at);
create index if not exists audit_sessions_role_department_idx
  on public.audit_sessions (role, department, started_at desc);
create index if not exists audit_sessions_device_browser_idx
  on public.audit_sessions (device_category, browser_name, started_at desc);

create index if not exists audit_events_occurred_idx
  on public.audit_events (occurred_at desc, id desc);
create index if not exists audit_events_session_idx
  on public.audit_events (session_id, occurred_at, id);
create index if not exists audit_events_actor_idx
  on public.audit_events (actor_user_id, occurred_at desc);
create index if not exists audit_events_role_department_idx
  on public.audit_events (actor_role, actor_department, occurred_at desc);
create index if not exists audit_events_route_idx
  on public.audit_events (route, occurred_at desc);
create index if not exists audit_events_action_idx
  on public.audit_events (action_category, event_name, occurred_at desc);
create index if not exists audit_events_record_idx
  on public.audit_events (record_type, record_id, occurred_at desc);
create index if not exists audit_events_outcome_idx
  on public.audit_events (outcome, occurred_at desc);
create index if not exists audit_events_request_idx
  on public.audit_events (request_id)
  where request_id is not null;
create unique index if not exists audit_events_session_dedupe_idx
  on public.audit_events (session_id, dedupe_key)
  where session_id is not null and dedupe_key is not null;
create index if not exists audit_events_search_idx
  on public.audit_events using gin (
    to_tsvector(
      'simple',
      coalesce(actor_name, '') || ' ' ||
      coalesce(event_name, '') || ' ' ||
      coalesce(action_label, '') || ' ' ||
      coalesce(feature, '') || ' ' ||
      coalesce(record_type, '') || ' ' ||
      coalesce(record_id, '') || ' ' ||
      coalesce(route, '')
    )
  );
create index if not exists audit_events_metadata_idx
  on public.audit_events using gin (metadata jsonb_path_ops);
create index if not exists audit_events_archive_occurred_idx
  on public.audit_events_archive (occurred_at desc, original_event_id desc);

create or replace function public.audit_reject_event_mutation()
returns trigger
language plpgsql
as $$
begin
  if current_setting('app.audit_maintenance', true) = 'on' then
    return case when tg_op = 'DELETE' then old else new end;
  end if;
  raise exception 'Audit events are append-only';
end;
$$;

drop trigger if exists audit_events_append_only on public.audit_events;
create trigger audit_events_append_only
before update or delete on public.audit_events
for each row execute function public.audit_reject_event_mutation();

drop trigger if exists audit_events_archive_append_only on public.audit_events_archive;
create trigger audit_events_archive_append_only
before update or delete on public.audit_events_archive
for each row execute function public.audit_reject_event_mutation();

create or replace function public.record_audit_event(p_event jsonb)
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_id bigint;
  v_prev_hash text;
  v_row_hash text;
  v_session_id uuid;
  v_actor_user_id integer;
  v_ip inet;
begin
  if coalesce(nullif(p_event->>'event_name', ''), '') = '' then
    raise exception 'event_name is required';
  end if;
  if coalesce(nullif(p_event->>'action_category', ''), '') = '' then
    raise exception 'action_category is required';
  end if;

  v_session_id := nullif(p_event->>'session_id', '')::uuid;
  v_actor_user_id := nullif(p_event->>'actor_user_id', '')::integer;
  v_ip := nullif(p_event->>'ip_address', '')::inet;

  perform pg_advisory_xact_lock(hashtext('public.audit_events.hash_chain'));
  select row_hash into v_prev_hash
  from public.audit_events
  order by id desc
  limit 1;

  v_row_hash := encode(
    digest(
      convert_to(
        jsonb_strip_nulls(p_event - 'row_hash' - 'prev_hash')::text ||
        '|' || coalesce(v_prev_hash, ''),
        'utf8'
      ),
      'sha256'
    ),
    'hex'
  );

  insert into public.audit_events (
    session_id, actor_user_id, actor_name, actor_role, actor_department,
    occurred_at, event_name, action_category, feature, route, page_title,
    previous_page, page_entered_at, page_left_at, duration_ms, action_label,
    record_type, record_id, outcome, request_id, dedupe_key, before_data,
    after_data, metadata, ip_address, prev_hash, row_hash
  )
  values (
    v_session_id,
    v_actor_user_id,
    nullif(p_event->>'actor_name', ''),
    nullif(p_event->>'actor_role', ''),
    nullif(p_event->>'actor_department', ''),
    coalesce(nullif(p_event->>'occurred_at', '')::timestamptz, now()),
    p_event->>'event_name',
    p_event->>'action_category',
    nullif(p_event->>'feature', ''),
    nullif(p_event->>'route', ''),
    nullif(p_event->>'page_title', ''),
    nullif(p_event->>'previous_page', ''),
    nullif(p_event->>'page_entered_at', '')::timestamptz,
    nullif(p_event->>'page_left_at', '')::timestamptz,
    greatest(0, nullif(p_event->>'duration_ms', '')::integer),
    nullif(p_event->>'action_label', ''),
    nullif(p_event->>'record_type', ''),
    nullif(p_event->>'record_id', ''),
    coalesce(nullif(p_event->>'outcome', ''), 'success'),
    nullif(p_event->>'request_id', '')::uuid,
    nullif(p_event->>'dedupe_key', ''),
    p_event->'before_data',
    p_event->'after_data',
    coalesce(p_event->'metadata', '{}'::jsonb),
    v_ip,
    v_prev_hash,
    v_row_hash
  )
  on conflict (session_id, dedupe_key)
    where session_id is not null and dedupe_key is not null
  do nothing
  returning id into v_id;

  if v_session_id is not null then
    update public.audit_sessions
    set last_activity_at = greatest(last_activity_at, now())
    where id = v_session_id
      and (v_actor_user_id is null or user_id = v_actor_user_id);
  end if;

  return v_id;
end;
$$;

create or replace function public.expire_stale_audit_sessions()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_timeout interval;
  v_count integer;
begin
  select make_interval(mins => session_timeout_minutes)
  into v_timeout
  from public.audit_retention_settings
  where id = 1;

  update public.audit_sessions
  set
    ended_at = last_activity_at,
    duration_seconds = greatest(0, extract(epoch from (last_activity_at - started_at))::integer),
    end_reason = 'heartbeat_timeout',
    status = 'timed_out'
  where status = 'active'
    and last_activity_at < now() - coalesce(v_timeout, interval '30 minutes');

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

create or replace function public.audit_safe_row_snapshot(
  p_table text,
  p_row jsonb
)
returns jsonb
language sql
immutable
as $$
  with allowed(keys) as (
    select case p_table
    when 'users' then array[
      'user_id', 'role', 'department', 'job_title', 'employment_status',
      'is_active', 'sidebar_access', 'updated_at'
    ]
    when 'appointments' then array[
      'appointment_id', 'job_id', 'customer_id', 'scheduled_time', 'status',
      'created_by', 'updated_by', 'created_at', 'updated_at'
    ]
    when 'jobs' then array[
      'id', 'job_number', 'type', 'status', 'assigned_to', 'job_division',
      'vhc_required', 'completion_status', 'tech_completion_status',
      'service_mode', 'queue_position', 'next_update_due', 'updated_at'
    ]
    when 'vhc_checks' then array[
      'vhc_id', 'job_id', 'section', 'approval_status', 'display_status',
      'authorization_state', 'severity', 'labour_hours', 'parts_cost',
      'total_override', 'labour_complete', 'parts_complete', 'approved_at',
      'approved_by', 'pre_pick_location', 'request_id', 'display_id',
      'authorized_total_gbp', 'declined_total_gbp', 'complete', 'updated_at'
    ]
    when 'parts_requests' then array[
      'request_id', 'job_id', 'requested_by', 'approved_by', 'quantity',
      'status', 'part_id', 'source', 'pre_pick_location', 'vhc_item_id',
      'fulfilled_by', 'created_at', 'updated_at'
    ]
    when 'job_notes' then array[
      'note_id', 'job_id', 'user_id', 'last_updated_by',
      'hidden_from_customer', 'linked_request_index', 'linked_vhc_id',
      'linked_part_id', 'created_at', 'updated_at'
    ]
    when 'job_files' then array[
      'file_id', 'job_id', 'file_type', 'uploaded_by', 'folder',
      'visible_to_customer', 'file_size', 'storage_type',
      'is_main_vhc_video', 'uploaded_at'
    ]
    when 'invoices' then array[
      'id', 'invoice_id', 'job_id', 'invoice_number', 'job_number',
      'account_id', 'paid', 'payment_method', 'payment_status', 'due_date',
      'invoice_date', 'total_parts', 'total_labour', 'total_vat', 'total',
      'labour_total', 'parts_total', 'consumables_total', 'vat',
      'grand_total', 'service_total', 'vat_total', 'invoice_total',
      'snapshot_version', 'sent_email_at', 'sent_portal_at',
      'created_at', 'updated_at'
    ]
    when 'messages' then array[
      'message_id', 'sender_id', 'receiver_id', 'thread_id', 'read',
      'saved_forever', 'created_at'
    ]
    else array[]::text[]
    end
  )
  select coalesce(jsonb_object_agg(entry.key, entry.value), '{}'::jsonb)
  from jsonb_each(coalesce(p_row, '{}'::jsonb)) as entry
  cross join allowed
  where entry.key = any(allowed.keys);
$$;

create or replace function public.capture_tracked_audit_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_headers jsonb := '{}'::jsonb;
  v_session_id uuid;
  v_session public.audit_sessions%rowtype;
  v_request_id uuid;
  v_ip text;
  v_before jsonb;
  v_after jsonb;
  v_record_id text;
  v_actor_id integer;
  v_actor_name text;
  v_actor_role text;
  v_actor_department text;
  v_operation text := lower(tg_op);
begin
  begin
    v_headers := coalesce(
      nullif(current_setting('request.headers', true), '')::jsonb,
      '{}'::jsonb
    );
  exception when others then
    v_headers := '{}'::jsonb;
  end;

  begin
    v_session_id := nullif(v_headers->>'x-audit-session-id', '')::uuid;
  exception when others then
    v_session_id := null;
  end;
  begin
    v_request_id := nullif(v_headers->>'x-request-id', '')::uuid;
  exception when others then
    v_request_id := null;
  end;

  if v_session_id is not null then
    select * into v_session
    from public.audit_sessions
    where id = v_session_id and status = 'active';
    if found then
      v_actor_id := v_session.user_id;
      v_actor_name := v_session.user_name;
      v_actor_role := v_session.role;
      v_actor_department := v_session.department;
    else
      v_session_id := null;
    end if;
  end if;

  v_before := case when tg_op = 'INSERT' then null
    else public.audit_safe_row_snapshot(tg_table_name, to_jsonb(old)) end;
  v_after := case when tg_op = 'DELETE' then null
    else public.audit_safe_row_snapshot(tg_table_name, to_jsonb(new)) end;

  if tg_op = 'UPDATE' and v_before = v_after then
    return new;
  end if;

  v_record_id := coalesce(
    (case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end) ->> tg_argv[0],
    ''
  );
  v_ip := split_part(coalesce(v_headers->>'x-forwarded-for', ''), ',', 1);

  perform public.record_audit_event(jsonb_strip_nulls(jsonb_build_object(
    'session_id', v_session_id,
    'actor_user_id', v_actor_id,
    'actor_name', v_actor_name,
    'actor_role', v_actor_role,
    'actor_department', v_actor_department,
    'event_name', tg_table_name || '_' || v_operation,
    'action_category', case when tg_op = 'DELETE' then 'delete' else 'record_change' end,
    'feature', tg_table_name,
    'record_type', tg_argv[1],
    'record_id', nullif(v_record_id, ''),
    'outcome', 'success',
    'request_id', v_request_id,
    'dedupe_key', case when v_request_id is null then null
      else 'db:' || v_request_id::text || ':' || tg_table_name || ':' || v_record_id || ':' || v_operation end,
    'before_data', v_before,
    'after_data', v_after,
    'metadata', jsonb_build_object('source', 'database_trigger'),
    'ip_address', nullif(v_ip, '')
  )));

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

do $$
declare
  v_target record;
begin
  for v_target in
    select *
    from (values
      ('users', 'user_id', 'user'),
      ('appointments', 'appointment_id', 'appointment'),
      ('jobs', 'id', 'job_card'),
      ('vhc_checks', 'vhc_id', 'vhc_item'),
      ('parts_requests', 'request_id', 'parts_request'),
      ('job_notes', 'note_id', 'job_note'),
      ('job_files', 'file_id', 'document'),
      ('invoices', 'id', 'invoice'),
      ('messages', 'message_id', 'message')
    ) as targets(table_name, primary_key, record_type)
  loop
    if to_regclass('public.' || v_target.table_name) is not null then
      execute format(
        'drop trigger if exists central_audit_change on public.%I',
        v_target.table_name
      );
      execute format(
        'create trigger central_audit_change after insert or update or delete on public.%I
         for each row execute function public.capture_tracked_audit_change(%L, %L)',
        v_target.table_name,
        v_target.primary_key,
        v_target.record_type
      );
    end if;
  end loop;
end
$$;

create or replace function public.archive_expired_audit_events(p_limit integer default 10000)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_live_cutoff timestamptz;
  v_archive_cutoff timestamptz;
  v_archived integer := 0;
  v_deleted integer := 0;
begin
  select
    now() - make_interval(days => live_days),
    now() - make_interval(days => archive_days)
  into v_live_cutoff, v_archive_cutoff
  from public.audit_retention_settings
  where id = 1;

  perform set_config('app.audit_maintenance', 'on', true);

  with candidates as (
    select *
    from public.audit_events
    where occurred_at < v_live_cutoff
    order by id
    limit greatest(1, least(coalesce(p_limit, 10000), 50000))
  ), archived as (
    insert into public.audit_events_archive (
      original_event_id, session_id, actor_user_id, actor_name, actor_role,
      actor_department, occurred_at, event_name, action_category, feature,
      route, page_title, previous_page, page_entered_at, page_left_at,
      duration_ms, action_label, record_type, record_id, outcome, request_id,
      dedupe_key, before_data, after_data, metadata, ip_address, prev_hash,
      row_hash, created_at
    )
    select
      id, session_id, actor_user_id, actor_name, actor_role, actor_department,
      occurred_at, event_name, action_category, feature, route, page_title,
      previous_page, page_entered_at, page_left_at, duration_ms, action_label,
      record_type, record_id, outcome, request_id, dedupe_key, before_data,
      after_data, metadata, ip_address, prev_hash, row_hash, created_at
    from candidates
    on conflict (original_event_id) do nothing
    returning original_event_id
  )
  select count(*) into v_archived from archived;

  delete from public.audit_events e
  where exists (
    select 1 from public.audit_events_archive a
    where a.original_event_id = e.id
  )
    and e.occurred_at < v_live_cutoff;

  delete from public.audit_events_archive
  where occurred_at < v_archive_cutoff;
  get diagnostics v_deleted = row_count;

  delete from public.audit_sessions s
  where coalesce(s.ended_at, s.last_activity_at) < v_archive_cutoff
    and not exists (
      select 1 from public.audit_events e where e.session_id = s.id
    );

  return jsonb_build_object(
    'archived', v_archived,
    'expired_deleted', v_deleted,
    'live_cutoff', v_live_cutoff,
    'archive_cutoff', v_archive_cutoff
  );
end;
$$;

alter table public.audit_sessions enable row level security;
alter table public.audit_sessions force row level security;
alter table public.audit_events enable row level security;
alter table public.audit_events force row level security;
alter table public.audit_events_archive enable row level security;
alter table public.audit_events_archive force row level security;
alter table public.audit_retention_settings enable row level security;
alter table public.audit_retention_settings force row level security;

revoke all on public.audit_sessions from anon, authenticated;
revoke all on public.audit_events from anon, authenticated;
revoke all on public.audit_events_archive from anon, authenticated;
revoke all on public.audit_retention_settings from anon, authenticated;
revoke all on function public.record_audit_event(jsonb) from public, anon, authenticated;
revoke all on function public.expire_stale_audit_sessions() from public, anon, authenticated;
revoke all on function public.archive_expired_audit_events(integer) from public, anon, authenticated;

grant usage on schema public to service_role;
grant select, insert, update on public.audit_sessions to service_role;
grant select, insert on public.audit_events to service_role;
grant select, insert on public.audit_events_archive to service_role;
grant select, insert, update on public.audit_retention_settings to service_role;
grant usage, select on all sequences in schema public to service_role;
grant execute on function public.record_audit_event(jsonb) to service_role;
grant execute on function public.expire_stale_audit_sessions() to service_role;
grant execute on function public.archive_expired_audit_events(integer) to service_role;

revoke update, delete, truncate on public.audit_events from service_role;
revoke update, delete, truncate on public.audit_events_archive from service_role;
revoke delete, truncate on public.audit_sessions from service_role;
revoke delete, truncate on public.audit_retention_settings from service_role;

comment on table public.audit_sessions is
  'Authenticated DMS application sessions. Browser roles have no direct access; the NextAuth API is the access boundary.';
comment on table public.audit_events is
  'Append-only, tamper-evident user activity and domain audit events.';
comment on table public.audit_events_archive is
  'Append-only long-term archive populated only by archive_expired_audit_events.';
comment on column public.audit_events.before_data is
  'Allowlisted, privacy-redacted values before an important change; never full form submissions.';
comment on column public.audit_events.after_data is
  'Allowlisted, privacy-redacted values after an important change; never full form submissions.';

commit;

notify pgrst, 'reload schema';
